CREATE TABLE b_awz_bpsearch_bpindex (
    ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    APP_ID varchar(256) NOT NULL DEFAULT '',
    MEMBER_ID varchar(256) NOT NULL DEFAULT '',
    BPID int NOT NULL DEFAULT 0,
    CRM_MODULE varchar(256) NOT NULL DEFAULT '',
    CRM_TYPE varchar(256) NOT NULL DEFAULT '',
    CRM_DOCUMENT varchar(256) NOT NULL DEFAULT '',
    ACT_NAME varchar(256) NOT NULL DEFAULT '',
    ACT_ID varchar(256) NOT NULL DEFAULT '',
    CODE varchar(256) NOT NULL DEFAULT '',
    DATE_UP timestamp NOT NULL,
    PARAMS text NOT NULL DEFAULT '',
    PRIMARY KEY (ID)
);

CREATE INDEX b_awz_bpsearch_bpindex_bpid ON b_awz_bpsearch_bpindex_bpid (bpid);

create table if not exists b_awz_bpsearch_names (
    ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ACT_TITLE varchar(256) NOT NULL DEFAULT '',
    ACT_NAME varchar(256) NOT NULL DEFAULT '',
    PRIMARY KEY (ID)
);

CREATE INDEX b_awz_bpsearch_names_act_name ON b_awz_bpsearch_names_act_id (act_name);